name: Build and Deploy to Azure

on:
  push:
    branches: [ main ]
    
permissions:
  id-token: write 
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Azure ACR
      uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }} 
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Crypfolio.API/Dockerfile
        push: true
        tags: crypcontainer.azurecr.io/crypfolio.api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Login to Azure
      uses: azure/login@v2
      with:
        #creds: ${{ secrets.AZURE_CREDENTIALS }}
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.WEBAPP_NAME }}
        images: ${{ secrets.ACR_LOGIN_SERVER }}/crypfolio.api:latest
