name: Build and Deploy to Azure

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Azure ACR
      uses: azure/docker-login@v2
      with:
        login-server: crypcontainer.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Crypfolio.API/Dockerfile
        push: true
        tags: crypcontainer.azurecr.io/crypfolio.api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: crypfolio-api  # Your App Service name
        images: crypcontainer.azurecr.io/crypfolio.api:latest
